export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTO_SUCCESS';
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTO_FAILURE';
export const FETCH_PHOTOS_FILTERED = 'FETCH_PHOTOSFILTERED';
export const FETCH_PHOTOS_FILTERED_SUCCESS = 'FETCH_PHOTOS_FILTERED_SUCCESS';
export const FETCH_PHOTOS_FILTERED_FAILURE = 'FETCH_PHOTOS_FILTERED_FAILURE';
